sys:
  uploadPath: /root/attach/
server:
  port: 444
  ssl:
      key-store: classpath:fullmusic.club.jks
      key-password: 159753
      key-store-type: JKS
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  resources:
    static-locations: file:/root/attach
  datasource:
    url: jdbc:mysql://94.191.15.204:3306/fullmusic
    username: root
    password: mmali159753
    driverClassName: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 200MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
      com:
       fullmusic:
          dao: debug